version: '3'

services:
  # Servidor web de PHP con Apache
  app:
    container_name: m1-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - m1-network

  db:
    image: mysql/mysql-server:latest
    container_name: m1-db
    restart: "no"
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=m1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - m1-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: m1-phpmyadmin
    restart: "no"
    ports:
      - "9090:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - m1-network

volumes:
  dbvolume:

networks:
  m1-network:
